const rupiah=(number)=>{return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR"}).format(number)};var hargasemua=[];var myArray=[];var datL=[];var cart={hPdt:null,hItems:null,hform:null,ps:null,items:{},iURL:"asset/image/",currency:"",total:0,save:()=>localStorage.setItem("cart",JSON.stringify(cart.items)),load:()=>{cart.items=localStorage.getItem("cart");if(cart.items==null){cart.items={}}else{cart.items=JSON.parse(cart.items)}},nuke:()=>{if(confirm("Apa anda yakin akan menghapus semua keranjang belanja anda")){cart.items={};localStorage.removeItem("cart");cart.list()}},init:()=>{fetch('https://cdn.jsdelivr.net/gh/micakucing/clopzkitchen@main/data.json').then(response=>{if(!response.ok){throw new Error(`HTTP error! status: ${response.status}`)}
return response.json()}).then(products=>{datL.push(products);cart.hPdt=document.getElementById("cart-products");cart.hItems=document.getElementById("cart-items");cart.ps=document.getElementById("detail-ps");document.getElementById("title-produk").innerHTML="Semua Produk";cart.hPdt.innerHTML="";cart.ps.innerHTML="";let template=document.getElementById("template-product").content,p,item;for(let id in datL[0]){p=datL[0][id];st=p.stok;if(st==='r'){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+p.img;item.querySelector(".p-name").textContent=p.name;item.querySelector(".p-price").textContent=rupiah(p.price);item.querySelector(".p-add").onclick=()=>cart.add(id);item.querySelector(".p-detail").onclick=()=>cart.detail(id);cart.hPdt.appendChild(item)}else{item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+p.img;item.querySelector(".p-name").textContent=p.name;item.querySelector(".p-price").textContent=rupiah(p.price);item.querySelector(".p-add").textContent='stok habis';item.querySelector(".p-add").onclick=()=>alert('maaf sudah stok habis');cart.hPdt.appendChild(item)}}
cart.load();cart.list()}).catch(error=>{console.error('Error loading JSON:',error)})},filter:(e)=>{attributeValue=event.target.getAttribute('data-product');document.getElementById("title-produk").innerHTML=attributeValue;cart.hPdt=document.getElementById("cart-products");cart.hItems=document.getElementById("cart-items");cart.hPdt.innerHTML="";let template=document.getElementById("template-product").content,p,item;x=1;for(let id in datL[0]){if(datL[0][id].category===e){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+datL[0][id].img;item.querySelector(".p-name").textContent=datL[0][id].name;item.querySelector(".p-price").textContent=rupiah(datL[0][id].price);item.querySelector(".p-add").onclick=()=>cart.add(id);item.querySelector(".p-detail").onclick=()=>cart.detail(id);cart.hPdt.appendChild(item);document.getElementById("title-produk").innerHTML=attributeValue+' <span style="display:block; font-size: 18px; margin: 10px 5px;">'+x+' total produk</span>';x++}else if(e==='*'){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+datL[0][id].img;item.querySelector(".p-name").textContent=datL[0][id].name;item.querySelector(".p-price").textContent=rupiah(datL[0][id].price);item.querySelector(".p-add").onclick=()=>cart.add(id);cart.hPdt.appendChild(item);console.log(x);x++}}
cart.load();cart.list()},list:()=>{cart.total=0;cart.hItems.innerHTML="";let item,empty=!0;for(let key in cart.items){if(cart.items.hasOwnProperty(key)){empty=!1;break}}
if(empty){item=document.createElement("div");item.innerHTML="Keranjang masih kosong";cart.hItems.appendChild(item);myArray=[]}else{let template=document.getElementById("template-cart").content,p,item;for(let id in cart.items){cart.total+=cart.items[id]*datL[0][id].price;harga=cart.items[id]*datL[0][id].price;console.log(cart.items[id])
item=template.cloneNode(!0);item.querySelector(".c-del").onclick=()=>cart.remove(id);item.querySelector(".namaproduk").textContent=datL[0][id].name;item.querySelector(".c-price").textContent=' ('+rupiah(datL[0][id].price)+')';item.querySelector(".c-qty").value=cart.items[id];item.querySelector(".c-qty").onchange=function(){cart.change(id,this.value)};cart.hItems.appendChild(item);object={name:datL[0][id].name,quantitas:cart.items[id]}}
item=document.createElement("div");item.className="c-total";item.id="c-total";item.innerHTML=`TOTAL: ${rupiah(cart.total)}`;cart.hItems.appendChild(item);let pricetot=document.getElementById("c-total").innerHTML;hargasemua=[rupiah(cart.total)]
item=document.getElementById("template-cart-checkout").content.cloneNode(!0);cart.hItems.appendChild(item)}},add:id=>{if(cart.items[id]==undefined){cart.items[id]=1}else{cart.items[id]++}
console.log(cart.items[id])
cart.save();cart.list()},change:(pid,qty)=>{if(qty<=0){myArray=[];delete cart.items[pid];cart.save();cart.list()}else{cart.items[pid]=qty;cart.total=0;for(let id in cart.items){cart.total+=cart.items[id]*datL[0][id].price;document.getElementById("c-total").innerHTML=`TOTAL: ${rupiah(cart.total)}`;hargasemua=[rupiah(cart.total)]
object={name:datL[0][id].name,quantitas:cart.items[id]}}}},remove:id=>{delete cart.items[id];cart.save();cart.list()},detail:ds=>{let template=document.getElementById("template-detail").content,p,item;cart.ps=document.getElementById("detail-ps");cart.hPdt.innerHTML="";itemx=template.cloneNode(!0);itemx.querySelector(".d-img").src=cart.iURL+datL[0][ds].img;p=datL[0][ds];document.getElementById("title-produk").innerHTML=p.name;itemx.querySelector(".des-produk").innerHTML='<h4 class="mt-4 mb-4">'+p.des+'</h4>';cart.ps.appendChild(itemx)},checkout:()=>{var namepro=[];var jumlah=[];var semuatotal;i=1;for(let id in cart.items){perharga=cart.items[id]*datL[0][id].price;semuatotal+=cart.items[id]*datL[0][id].price;namepro.push(i+'. '+datL[0][id].name+' - ( '+cart.items[id]+' * '+datL[0][id].price+' = '+perharga+')')
i++}
totalfinal=encodeURIComponent('\n\nTOTAL BAYAR: '+rupiah(cart.total)+'\n terima kasih sudah belanja di clopz kitchen')
content=namepro;alert("terima kasih sudah belanja cemilan di clopz kitchen \n \n sebentar lagi anda akan di hubungkan ke admin clopz kitchen");const whatsappLink=`https://api.whatsapp.com/send?phone=6285718787490&text=${encodeURIComponent(content.join('\n'))} ${totalfinal}`;namepro=[];myArray=[];cart.items={};localStorage.removeItem("cart");cart.total=0;cart.hItems.innerHTML="";window.open(whatsappLink,'_blank');window.location.reload()}};window.addEventListener("DOMContentLoaded",cart.init)