const rupiah=(number)=>{return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR"}).format(number)};var hargasemua=[];var myArray=[];var cart={hPdt:null,hItems:null,hform:null,items:{},iURL:"asset/image/",currency:"",total:0,save:()=>localStorage.setItem("cart",JSON.stringify(cart.items)),load:()=>{cart.items=localStorage.getItem("cart");if(cart.items==null){cart.items={}}else{cart.items=JSON.parse(cart.items)}},nuke:()=>{if(confirm("Apa anda yakin akan menghapus semua keranjang belanja anda")){cart.items={};localStorage.removeItem("cart");cart.list()}},init:()=>{cart.hPdt=document.getElementById("cart-products");cart.hItems=document.getElementById("cart-items");cart.hPdt.innerHTML="";let template=document.getElementById("template-product").content,p,item;for(let id in products){p=products[id];st=p.stok;if(st==='r'){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+p.img;item.querySelector(".p-name").textContent=p.name;item.querySelector(".p-price").textContent=rupiah(p.price);item.querySelector(".p-add").onclick=()=>cart.add(id);cart.hPdt.appendChild(item)}else{item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+p.img;item.querySelector(".p-name").textContent=p.name;item.querySelector(".p-price").textContent=rupiah(p.price);item.querySelector(".p-add").textContent='stok habis';item.querySelector(".p-add").onclick=()=>alert('maaf sudah stok habis');cart.hPdt.appendChild(item)}}
cart.load();cart.list()},filter:(e)=>{cart.hPdt=document.getElementById("cart-products");cart.hItems=document.getElementById("cart-items");attributeValue=event.target.getAttribute('data-product');document.getElementById("title-produk").innerHTML=attributeValue;cart.hPdt.innerHTML="";let template=document.getElementById("template-product").content,p,item;x=1;for(let id in products){if(products[id].category===e){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+products[id].img;item.querySelector(".p-name").textContent=products[id].name;item.querySelector(".p-price").textContent=rupiah(products[id].price);item.querySelector(".p-add").onclick=()=>cart.add(id);cart.hPdt.appendChild(item);document.getElementById("title-produk").innerHTML=attributeValue+' <span style="display:block; font-size: 18px; margin: 10px 5px;">'+x+' total produk</span>';x++}else if(e==='*'){item=template.cloneNode(!0);item.querySelector(".p-img").src=cart.iURL+products[id].img;item.querySelector(".p-name").textContent=products[id].name;item.querySelector(".p-price").textContent=rupiah(products[id].price);item.querySelector(".p-add").onclick=()=>cart.add(id);cart.hPdt.appendChild(item);console.log(x);x++}}
cart.load();cart.list()},list:()=>{cart.total=0;cart.hItems.innerHTML="";let item,empty=!0;for(let key in cart.items){if(cart.items.hasOwnProperty(key)){empty=!1;break}}
if(empty){item=document.createElement("div");item.innerHTML="Keranjang masih kosong";cart.hItems.appendChild(item);myArray=[]}else{let template=document.getElementById("template-cart").content,p,item;for(let id in cart.items){cart.total+=cart.items[id]*products[id].price;harga=cart.items[id]*products[id].price;console.log(cart.items[id])
item=template.cloneNode(!0);item.querySelector(".c-del").onclick=()=>cart.remove(id);item.querySelector(".namaproduk").textContent=products[id].name;item.querySelector(".c-price").textContent=' ('+rupiah(products[id].price)+')';item.querySelector(".c-qty").value=cart.items[id];item.querySelector(".c-qty").onchange=function(){cart.change(id,this.value)};cart.hItems.appendChild(item);object={name:products[id].name,quantitas:cart.items[id]}}
item=document.createElement("div");item.className="c-total";item.id="c-total";item.innerHTML=`TOTAL: ${rupiah(cart.total)}`;cart.hItems.appendChild(item);let pricetot=document.getElementById("c-total").innerHTML;hargasemua=[rupiah(cart.total)]
item=document.getElementById("template-cart-checkout").content.cloneNode(!0);cart.hItems.appendChild(item)}},add:id=>{if(cart.items[id]==undefined){cart.items[id]=1}else{cart.items[id]++}
console.log(cart.items[id])
cart.save();cart.list()},change:(pid,qty)=>{if(qty<=0){myArray=[];delete cart.items[pid];cart.save();cart.list()}else{cart.items[pid]=qty;cart.total=0;for(let id in cart.items){cart.total+=cart.items[id]*products[id].price;document.getElementById("c-total").innerHTML=`TOTAL: ${rupiah(cart.total)}`;hargasemua=[rupiah(cart.total)]
object={name:products[id].name,quantitas:cart.items[id]}}}},remove:id=>{delete cart.items[id];cart.save();cart.list()},checkout:()=>{var namepro=[];var jumlah=[];var semuatotal;i=1;for(let id in cart.items){perharga=cart.items[id]*products[id].price;semuatotal+=cart.items[id]*products[id].price;namepro.push(i+'. '+products[id].name+' - ( '+cart.items[id]+' * '+products[id].price+' = '+perharga+')')
i++}
totalfinal=encodeURIComponent('\n\nTOTAL BAYAR: '+rupiah(cart.total)+'\n terima kasih sudah belanja di clopz kitchen')
content=namepro;alert("terima kasih sudah belanja cemilan di clopz kitchen \n \n sebentar lagi anda akan di hubungkan ke admin clopz kitchen");const whatsappLink=`https://api.whatsapp.com/send?phone=6285718787490&text=${encodeURIComponent(content.join('\n'))} ${totalfinal}`;namepro=[];myArray=[];cart.items={};localStorage.removeItem("cart");cart.total=0;cart.hItems.innerHTML="";window.open(whatsappLink,'_blank');window.location.reload()}};window.addEventListener("DOMContentLoaded",cart.init)